name = "MLJClusteringInterface"
uuid = "d354fa79-ed1c-40d4-88ef-b8c7bd1568af"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>", "Thibaut Lienart <thibaut.lienart@gmail.com>", "Okon Samuel <okonsamuel50@gmail.com>"]
version = "0.1.10"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"

[compat]
Clustering = "0.15"
Distances = "0.9, 0.10"
MLJModelInterface = "1.4"
julia = "1.6"
