name = "MLJClusteringInterface"
uuid = "d354fa79-ed1c-40d4-88ef-b8c7bd1568af"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>", "Thibaut Lienart <thibaut.lienart@gmail.com>", "Okon Samuel <okonsamuel50@gmail.com>"]
version = "0.1.4"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"

[compat]
Clustering = "0.14"
Distances = "0.9, 0.10"
MLJModelInterface = "0.3.6,0.4, 1.0"
NearestNeighbors = "0.4"
julia = "1"
